<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>FreeMarker 中文官方参考手册</h1>
<span>name ===</span><span> ${user.name} </span>
<span>desc ===</span><span> ${user.desc} </span>
</body>
</html>