<!doctype html>
<html lang="en" class="page-type-book">
<meta charset="utf-8">
<title>FreeMarker 演示页面</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="format-detection" content="telephone=no">
<meta property="og:site_name" content="FreeMarker 中文官方参考手册">
<meta property="og:title" content="FreeMarker 中文官方参考手册">
<meta property="og:locale" content="zh_CN">
<meta property="og:url" content="http://freemarker.org/docs/toc.html">
<body>

<h1>首页</h1>
</br>
<div>
 <a href="fm/index">跳到另一个页面</a>
</div>
</br>
<div>
  <p> 输入名字进行跳转 </p>
  <form action="helloworld" method="post">
  <input name="name" placeholder="请输入名字"/>
  <input type="submit" value="提交"/>
  </form>
</div>

</body>
</html>
