
dubbo:
  application:
    name: playground-apache-dubbo-provider
    enable-file-cache: false
  protocol:
    name: dubbo
#    port: -1
    port: 2200
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181