spring:
  application:
    name: playground-spring-boot-freemarker
  freemarker:
    enabled": true
    preferFileSystemAccess: true
    cache: false #关闭模板缓存，方便测试
    allow-request-override: false
    allow-session-override: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
